title: mold
author: Yree
email: mold@yree.io
url: https://yree.io
baseurl: "/mold"
description: A minimal, optimized, lightweight design for static sites.

git_repo: yree/mold

permalink: /:slug

favicon: favicon.svg
goat_counter: yree

remote_theme: yree/mold

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
